// src/app/hospital-viladecans/hospital-viladecans.component.ts
import { Component } from '@angular/core';
import { HeroComponent } from '../hero/hero.component';
import { NavbarComponent } from '../navbar/navbar.component';
import { FooterComponent } from '../footer/footer.component';

@Component({
  selector: 'app-hospital-viladecans',
  standalone: true,
  imports: [HeroComponent, NavbarComponent, FooterComponent],
  templateUrl: './hospital-viladecans.component.html',
  styleUrl: './hospital-viladecans.component.scss'
})
export class HospitalViladecansComponent {

}

<app-navbar/>

<main className="main-container">
    <section>
      <article class='project-article'>
        <h1>Hospital de Viladecans VR Experience</h1>
        <div class='project-container'>
          <p>
            El proyecto del hospital de viladecans es un desarrollo de realidad virtual que hicimos de la mano del hospital
            para conmemorar el antiguo hospital de San Lorenzo. Viladecans en 2019 ha mejorado la infraestructura de su
            complejo hospitalario para poder proporcionar un mejor servicio, y es por ello que se ha desarrollado una
            experiencia de realidad virtual para recorrer la história del antiguo hospital.
          </p>
          <p>
            La experiencia está compuesta de diferentes escenas en las que el usuario podrá visualizar contenidos interactivos con el objetivo de poder
            ver toda la historia, además de todos los cambios y mejoras que se han llevado a cabo. La experiencia tiene una duracion media de 10 minutos.
          </p>
        </div>
      </article>
      <article class='project-trailer'>
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/o-fQncsQrEE?si=KzQN2WInED8WL8qd" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>        <em>Tráiler de la experiencia Hospital Viladecans VR Experience</em>
      </article>
      <article class="mediakit-container">
        <h2>Contenidos</h2>
        <p>Todo el contenido dentro del media kit es de uso público, cualquier persona o empresa puede usar estos contenidos.</p>
        <em>Si necesitas cualquier contenido adicional que no está disponible en nuestro presskit, <a href="/contact" style="color: blue;">contacta con nosotros.</a></em>
        <a class="btn" style="margin-top: 2%; margin-bottom: 2%;" href="assets/sources/hospital-viladecans_mediakit.rar" download>Media Kit</a>
      </article>
      <article class='project-gallery-article'>
        <h2>Galería</h2>
        <div class='project-gallery-container'>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-1.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-2.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-3.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-4.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-4.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-4.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-4.png' alt='Imagen projecto Viladecans VR 1'/>
          <img src='assets/projects/hospital-viladecans-vr-experience/hospital-viladecans-4.png' alt='Imagen projecto Viladecans VR 1'/>
        </div>
      </article>
    </section>
  </main>

  <app-footer/>

// src/pages/projects/HospitalViladecans.tsx
import '../../styles/pages/projects/HospitalViladecans.css';
import ImagenProjecto1 from '../../assets/projects/hospital-viladecans-vr-experience/HospitalViladecans-1.png';
import ImagenProjecto2 from '../../assets/projects/hospital-viladecans-vr-experience/HospitalViladecans-1.png';
import ImagenProjecto3 from '../../assets/projects/hospital-viladecans-vr-experience/HospitalViladecans-1.png';
import ImagenProjecto4 from '../../assets/projects/hospital-viladecans-vr-experience/HospitalViladecans-1.png';
import ImagenProjecto5 from '../../assets/projects/hospital-viladecans-vr-experience/HospitalViladecans-1.png';


const HospitalViladecans = () => {
  return (
    <>
    <main className="main-container">
      <section>
        <h1>Hospital Viladecans - VR Experience</h1>
        <article>
            
        </article>
        <article className='project-article'>
          <div className='project-container'>
            <p>
              El proyecto del hospital de viladecans es un desarrollo de realidad virtual que hicimos de la mano del hospital
              para conmemorar el antiguo hospital de San Lorenzo. Viladecans en 2019 ha mejorado la infraestructura de su
              complejo hospitalario para poder proporcionar un mejor servicio, y es por ello que se ha desarrollado una
              experiencia de realidad virtual para recorrer la história del antiguo hospital.
            </p>
          </div>
        </article>
        <article className='project-gallery-article'>
          <div className='project-gallery-container'>
            <img src={ ImagenProjecto1 } alt='Imagen projecto Viladecans VR 1'/>
            <img src={ ImagenProjecto2 } alt='Imagen projecto Viladecans VR 2'/>
            <img src={ ImagenProjecto3 } alt='Imagen projecto Viladecans VR 3'/>
            <img src={ ImagenProjecto4 } alt='Imagen projecto Viladecans VR 4'/>
            <img src={ ImagenProjecto5 } alt='Imagen projecto Viladecans VR 5'/>
          </div>
        </article>
      </section>
    </main>
    </>
  );
};

export default HospitalViladecans;
